# $Id: Makefile,v 1.1.1.1 2010/03/11 21:07:19 kris Exp $
# Makefile for the Sun Boot PROM interface library under
# Linux.
#

EXTRA_AFLAGS := -ansi
EXTRA_CFLAGS := -Werror

lib-y   := bootstr.o devops.o init.o misc.o \
	   tree.o console.o printf.o p1275.o cif.o
